version: '3.8'

services:

  movies-db:
    image: mysql:8.0.36-oraclelinux8
    container_name: movies-db-mysql
    domainname: movies-db-mysql.local
    command:
      - --sql_mode=NO_ENGINE_SUBSTITUTION
      - --skip-log-bin
      - --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies_db
      TZ: UTC
    volumes:
      - ./init_movies_db.sql:/docker-entrypoint-initdb.d/init_movies_db.sql
    ports:
      - "3310:3306"
    networks:
      - movies.local

  rentals-db:
    image: mysql:8.0.36-oraclelinux8
    container_name: movies-rents-db-mysql
    domainname: movies-rents-db-mysql.local
    command:
      - --sql_mode=NO_ENGINE_SUBSTITUTION
      - --skip-log-bin
      - --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies_rents_db
      TZ: UTC
    volumes:
      - ./init_movies_rents_db.sql:/docker-entrypoint-initdb.d/init_movies_rents_db.sql
    ports:
      - "3311:3306"
    networks:
      - movies.local

networks:
  movies.local: