CREATE DATABASE IF NOT EXISTS movies_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE movies_db;

CREATE TABLE IF NOT EXISTS movies
(
    id          BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    director    VARCHAR(255),
    year        INT,
    synopsis    TEXT,
    trailer_url VARCHAR(255),
    actors      VARCHAR(255),
    category    VARCHAR(255),
    language    VARCHAR(255),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

INSERT INTO movies (title, director, year, synopsis, trailer_url, actors, category, language)
VALUES ('El Último Reino', 'Edward Bazalgette', 2024,
        'En la era de los vikingos y la conquista, un hombre lucha por su lugar en el mundo.',
        'https://www.youtube.com/watch?v=eqCYw_o5lng', 'Alexander Dreymon, David Dawson, Emily Cox', 'Acción, Drama',
        'Inglés'),
       ('Las Aventuras de Tintín', 'Steven Spielberg', 2011,
        'El joven reportero Tintín y su perro Milú se embarcan en una aventura para descubrir un tesoro.',
        'https://www.youtube.com/watch?v=AOBlXnJRVC0', 'Jamie Bell, Andy Serkis, Daniel Craig', 'Aventura, Animación',
        'Español'),
       ('El Libro de la Selva 2', 'Steve Trenbirth', 2003,
        'Mowgli debe elegir entre la vida en la aldea o regresar a la selva con sus amigos animales.',
        'https://www.youtube.com/watch?v=juQvxs92q7E', 'Haley Joel Osment, John Goodman, Mae Whitman',
        'Animación, Aventura', 'Inglés'),
       ('Los Cazafantasmas', 'Jason Reitman', 2021,
        'Una nueva generación de cazafantasmas se enfrenta a amenazas paranormales.',
        'https://www.youtube.com/watch?v=1I1JrPgoM8U', 'Finn Wolfhard, Mckenna Grace, Paul Rudd', 'Comedia, Fantasía',
        'Español'),
       ('La Sombra del Guerrero', 'Scott Cooper', 1980,
        'Un guerrero solitario busca redención mientras enfrenta enemigos del pasado.',
        'https://www.youtube.com/watch?v=Fvn3giWYZTg', 'Christian Bale, Rosamund Pike, Wes Studi', 'Acción, Drama',
        'Inglés'),
       ('El Hombre de la Máscara de Hierro', 'Randall Wallace', 1998,
        'Los mosqueteros deben rescatar a un prisionero con una máscara de hierro para salvar a Francia.',
        'https://www.youtube.com/watch?v=gnNt7l2nA_o', 'Leonardo DiCaprio, Jeremy Irons, John Malkovich',
        'Aventura, Drama', 'Inglés'),
       ('La Leyenda del Tesoro Perdido', 'Jon Turteltaub', 2004,
        'Un cazador de tesoros descifra pistas ocultas para encontrar un tesoro histórico.',
        'https://www.youtube.com/watch?v=K7m1grWSMCA', 'Nicolas Cage, Diane Kruger, Justin Bartha', 'Aventura, Acción',
        'Español'),
       ('El Príncipe del Desierto', 'Jean-Jacques Annaud', 2011,
        'Un joven príncipe se enfrenta a la responsabilidad y los conflictos de su herencia.',
        'https://www.youtube.com/watch?v=IpG6GSkpd8E', 'Tahar Rahim, Mark Strong, Antonio Banderas', 'Drama, Aventura',
        'Español'),
       ('El Secreto de la Pirámide', 'Barry Levinson', 1985,
        'Una joven versión de Sherlock Holmes y su amigo Watson descubren un misterio en Londres.',
        'https://www.youtube.com/watch?v=vFmc7vn5wSA', 'Nicholas Rowe, Alan Cox, Sophie Ward', 'Misterio, Aventura',
        'Español'),
       ('Las Crónicas de Narnia', 'Andrew Adamson', 2005,
        'Cuatro hermanos descubren un mundo mágico a través de un armario y se convierten en héroes.',
        'https://www.youtube.com/watch?v=XFQwHiEdJdQ', 'Georgie Henley, Skandar Keynes, William Moseley',
        'Fantasía, Aventura', 'Español'),
       ('La Maldición del Rey Escorpión', 'Chuck Russell', 2002,
        'Un guerrero se enfrenta a un ejército de maldad para salvar su reino.',
        'https://www.youtube.com/watch?v=b7nmYiZ6cAg', 'Dwayne Johnson, Kelly Hu, Michael Clarke Duncan',
        'Acción, Aventura', 'Español'),
       ('El Caballero Oscuro: La Leyenda Renace', 'Christopher Nolan', 2012,
        'Batman regresa para proteger Gotham de nuevas amenazas.', 'https://www.youtube.com/watch?v=e0qwi-4iOpE',
        'Christian Bale, Tom Hardy, Anne Hathaway', 'Acción, Suspense', 'Español'),
       ('El Hobbit: Un Viaje Inesperado', 'Peter Jackson', 2012,
        'Bilbo Baggins se une a un grupo de enanos en una aventura para recuperar su hogar de un dragón.',
        'https://www.youtube.com/watch?v=tUB_FT4sSOg', 'Martin Freeman, Ian McKellen, Richard Armitage',
        'Fantasía, Aventura', 'Español'),
       ('El Hobbit: La Desolación de Smaug', 'Peter Jackson', 2013,
        'Bilbo y los enanos continúan su viaje para reclamar Erebor del dragón Smaug.',
        'https://www.youtube.com/watch?v=sI8OQRXhcZE', 'Martin Freeman, Ian McKellen, Richard Armitage',
        'Fantasía, Aventura', 'Español'),
       ('El Hobbit: La Batalla de los Cinco Ejércitos', 'Peter Jackson', 2014,
        'La batalla final por la Montaña Solitaria enfrenta a enanos, elfos y hombres contra las fuerzas oscuras.',
        'https://www.youtube.com/watch?v=oSTb50mGJe0', 'Martin Freeman, Ian McKellen, Richard Armitage',
        'Fantasía, Aventura', 'Inglés'),
       ('Avatar: El Camino del Agua', 'James Cameron', 2022,
        'Jake Sully y Neytiri luchan por proteger a su familia y su hogar en Pandora.',
        'https://www.youtube.com/watch?v=kPMi_VxqcUc', 'Sam Worthington, Zoe Saldana, Sigourney Weaver',
        'Ciencia Ficción, Aventura', 'Español'),
       ('Blade Runner 2049', 'Denis Villeneuve', 2017,
        'Un nuevo blade runner descubre un secreto que podría desatar el caos en la sociedad.',
        'https://www.youtube.com/watch?v=dZOaI_Fn5o4', 'Ryan Gosling, Harrison Ford, Ana de Armas',
        'Ciencia Ficción, Suspense', 'Español');
